#!/usr/bin/env node
/**
 * Reddit MCP – Credential Setup
 *
 * Interactively prompts for Reddit credentials and stores them securely in the
 * OS keychain (macOS Keychain, Windows Credential Manager, or Linux Secret
 * Service).  Credentials are NEVER written to any file on disk by this script.
 *
 * Usage:
 *   npm run setup
 */

import * as readline from "readline";
import * as fs from "fs";
import * as path from "path";
import { saveToKeychain, KEYCHAIN_SERVICE, keychainHasCredentials } from "./credentials";
import type { Credentials } from "./credentials";

// ---------------------------------------------------------------------------
// Terminal helpers
// ---------------------------------------------------------------------------

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
  terminal: true,
});

function prompt(question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer.trim());
    });
  });
}

/**
 * Prompt for a password without echoing characters.
 * Falls back to normal readline if stdin is not a TTY (e.g. piped input in tests).
 */
function promptPassword(question: string): Promise<string> {
  return new Promise((resolve) => {
    if (!process.stdin.isTTY) {
      // Non-interactive: read normally (e.g. piped in CI).
      rl.question(question, (answer) => resolve(answer.trim()));
      return;
    }

    process.stdout.write(question);

    // Switch to raw mode to read character-by-character.
    process.stdin.setRawMode(true);
    process.stdin.resume();
    process.stdin.setEncoding("utf8");

    let password = "";

    const onData = (char: string): void => {
      if (char === "\n" || char === "\r" || char === "\u0004" /* EOF */) {
        process.stdin.setRawMode(false);
        process.stdin.pause();
        process.stdin.removeListener("data", onData);
        process.stdout.write("\n");
        resolve(password);
      } else if (char === "\u0003" /* Ctrl+C */) {
        process.stdout.write("\n");
        process.exit(130);
      } else if (char === "\u007F" /* Backspace */) {
        if (password.length > 0) {
          password = password.slice(0, -1);
          process.stdout.write("\b \b");
        }
      } else {
        password += char;
        process.stdout.write("*");
      }
    };

    process.stdin.on("data", onData);
  });
}

// ---------------------------------------------------------------------------
// Fallback: write .env file when keychain is unavailable
// ---------------------------------------------------------------------------

function writeEnvFile(creds: Credentials): void {
  const envPath = path.resolve(process.cwd(), ".env");
  const content = [
    "# Reddit MCP credentials – generated by `npm run setup`",
    "# This file is gitignored. Do not commit it.",
    "",
    `REDDIT_CLIENT_ID=${creds.clientId}`,
    `REDDIT_CLIENT_SECRET=${creds.clientSecret}`,
    `REDDIT_USERNAME=${creds.username}`,
    `REDDIT_PASSWORD=${creds.password}`,
    `REDDIT_USER_AGENT=${creds.userAgent}`,
    "",
  ].join("\n");

  fs.writeFileSync(envPath, content, { mode: 0o600 }); // owner read/write only
  console.log(`\n⚠  Credentials written to ${envPath} (permissions: 600).`);
  console.log("   This file is gitignored, but treat it with care.");
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  console.log("╔═══════════════════════════════════════╗");
  console.log("║       Reddit MCP – Credential Setup   ║");
  console.log("╚═══════════════════════════════════════╝");
  console.log();
  console.log("Credentials will be stored in the OS keychain (macOS Keychain,");
  console.log("Windows Credential Manager, or Linux Secret Service).");
  console.log("They will NEVER be written to any file that could end up in");
  console.log("version control.");
  console.log();

  // Warn if credentials already exist.
  const hasExisting = await keychainHasCredentials();
  if (hasExisting) {
    const overwrite = await prompt(
      "⚠  Existing credentials found in the keychain. Overwrite? [y/N] "
    );
    if (overwrite.toLowerCase() !== "y") {
      console.log("Aborted. Existing credentials unchanged.");
      rl.close();
      return;
    }
    console.log();
  }

  console.log("You need a Reddit 'script'-type app.  Create one at:");
  console.log("  https://www.reddit.com/prefs/apps");
  console.log();

  const clientId = await prompt("Reddit App Client ID:     ");
  const clientSecret = await promptPassword("Reddit App Client Secret: ");
  const username = await prompt("Reddit Username:          ");
  const password = await promptPassword("Reddit Password:          ");

  const defaultAgent = `node:reddit-mcp:v1.0.0 (by /u/${username || "you"})`;
  const userAgentInput = await prompt(
    `User-Agent [${defaultAgent}]: `
  );
  const userAgent = userAgentInput || defaultAgent;

  if (!clientId || !clientSecret || !username || !password) {
    console.error("\n✖  All fields are required. Setup cancelled.");
    rl.close();
    process.exit(1);
  }

  const creds: Credentials = { clientId, clientSecret, username, password, userAgent };

  rl.close();

  // Try keychain first; fall back to .env file.
  try {
    await saveToKeychain(creds);
    console.log(`\n✔  Credentials stored securely in the OS keychain under service "${KEYCHAIN_SERVICE}".`);
    console.log("   The MCP server will load them from the keychain automatically.");
    console.log("   No environment variables or config files are needed.");
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    console.warn(`\n⚠  Could not save to keychain: ${message}`);
    console.log("   Falling back to .env file...");
    writeEnvFile(creds);
  }

  console.log("\nSetup complete. You can now start the MCP server:");
  console.log("  npm start");
}

main().catch((err) => {
  console.error("Setup failed:", err instanceof Error ? err.message : String(err));
  rl.close();
  process.exit(1);
});
